"""
challenge_utils -- prebuilt helpers for the Rover planning challenge.

GENERATED by build_notebooks.py -- do not hand-edit. Loads the terrain data and
defines the visualizer + the official metric so the candidate notebook only has
to import them. The true terrain cost stays hidden behind `path_cost` /
`evaluate` (it lives in meta['true_cost'] as an opaque grid); recovering it from
the demos is the point of the challenge, so resist peeking here.
"""
import os
import numpy as np
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))

def _load(name):
    return os.path.join(_HERE, name)

field = np.load(_load('field.npy'))                       # (H, W, 3)
demos = np.load(_load('demos.npy'), allow_pickle=True)    # object array of (T,2)
meta  = np.load(_load('meta.npz'))
start, goal = meta['start'], meta['goal']
H, W = field.shape[:2]
ROCK, MUD, SLOPE = 0, 1, 2


def show(paths=None, cost_map=None, title=''):
    '''Plot the terrain (or a cost map), the expert demos (gray), and any
    candidate paths (lime), with start (white o) and goal (white *).'''
    fig, ax = plt.subplots(figsize=(6, 6))
    # Default to the true cost map when no cost_map is passed, so both views
    # use the same viridis colormap.
    grid = np.asarray(cost_map if cost_map is not None else meta['true_cost'], float)
    # Rocks carry a huge sentinel/penalty that would swamp the color scale and
    # flatten all the mud/slope variation. Scale the colormap to the terrain
    # (non-rock) range and render rock cells in the colormap's "over" color.
    rock = field[..., ROCK] == 1
    terrain = grid[~rock]
    cmap = plt.get_cmap('viridis').copy()
    cmap.set_over('0.6')   # rocks shown distinctly (gray)
    vmin = float(terrain.min()) if terrain.size else 0.0
    vmax = float(terrain.max()) if terrain.size else 1.0
    ax.imshow(grid, origin='lower', cmap=cmap, vmin=vmin, vmax=vmax)
    for d in demos:
        d = np.asarray(d)
        ax.plot(d[:, 0], d[:, 1], '0.7', lw=1, alpha=.7)
        # Tiny per-demo endpoint markers (gray, to match the demo line): each
        # demo runs between its OWN start (o) and goal (*), so mark both.
        ax.plot(d[0, 0],  d[0, 1],  'o', color='0.5', ms=3, alpha=.8)
        ax.plot(d[-1, 0], d[-1, 1], '*', color='0.5', ms=5, alpha=.8)
    if paths is not None:
        if isinstance(paths, np.ndarray) and paths.ndim == 2:
            paths = [paths]
        for p in paths:
            p = np.asarray(p)
            ax.plot(p[:, 0], p[:, 1], 'lime', lw=2)
    ax.plot(*start, 'wo', ms=8); ax.plot(*goal, 'w*', ms=14)
    ax.set_title(title); ax.set_xlim(0, W); ax.set_ylim(0, H)
    plt.show()


# ===== PRE-BUILT METRIC -- see docstrings for path_cost/evaluate.
# The true per-step terrain cost is an opaque grid in meta['true_cost']; don't
# peek -- recovering it from the demos is the point of the challenge.
EXPERT_COST = float(meta['expert_cost'])
TOL = float(meta['tol'])
_TRUE_COST = meta['true_cost']                 # (H,W) opaque scoring grid
_ROCK = float(meta['rock_sentinel'])           # cells >= this are rock
_STEP = 0.5                                    # path-integral resampling (cells)
# Penalty applied to rock / forbidden cells. A large finite number (not inf)
# so path_cost stays numerically well-behaved -- every rollout the planner
# scores has a comparable cost even if it crosses an obstacle, which avoids
# argmin stalling on a sea of inf values.
ROCK_PENALTY = 1e6
_HI = ROCK_PENALTY / 2                          # cells >= this count as "rock"
# Two views of the hidden grid: rocks penalized (to detect crossings) and rocks
# zeroed (honest terrain-only cost reported against the bar).
_TRUE_COST_PEN  = np.where(_TRUE_COST >= _ROCK, ROCK_PENALTY, _TRUE_COST)
_TRUE_COST_BARE = np.where(_TRUE_COST >= _ROCK, 0.0,          _TRUE_COST)

def _resample_steps(path):
    '''Resample `path` to ~uniform _STEP spacing; return (rx, ry, in_bounds).'''
    path = np.asarray(path, float)
    seg = np.linalg.norm(np.diff(path, axis=0), axis=1)
    L = float(seg.sum())
    if L < 1e-9:
        return None
    s = np.concatenate([[0.0], np.cumsum(seg)])
    n = max(2, int(L / _STEP) + 1)
    u = np.linspace(0, L, n)
    xs = np.interp(u, s, path[:, 0]); ys = np.interp(u, s, path[:, 1])
    rx = np.rint(xs).astype(np.intp)
    ry = np.rint(ys).astype(np.intp)
    in_bounds = (rx >= 0) & (rx <= W - 1) & (ry >= 0) & (ry <= H - 1)
    return rx, ry, in_bounds

def path_cost(path, cost_map):
    '''Integrate cost_map along path; return total cost as a float (lower is
    better, empty path -> inf). Resamples to ~uniform spacing first, so the
    result is independent of waypoint count. Score rollouts with this inside
    your planner. Mark "do not enter" cells with ROCK_PENALTY (not np.inf) so
    every rollout stays comparable; out-of-bounds points are charged the same.
    '''
    cost_map = np.asarray(cost_map, float)
    if cost_map.shape != (H, W):
        raise ValueError(f'cost_map must have shape {(H, W)}, got {cost_map.shape}')
    rs = _resample_steps(path)
    if rs is None:
        return float('inf')
    rx, ry, in_bounds = rs
    # In-bounds points contribute their cell cost; out-of-bounds points are
    # charged ROCK_PENALTY.
    cells = np.where(in_bounds, cost_map[np.clip(ry, 0, H - 1), np.clip(rx, 0, W - 1)],
                     ROCK_PENALTY)
    return float(cells.sum() * _STEP)

def evaluate(path, cost_map):
    '''Official PASS/FAIL scorer. Returns True iff the path passes.

    Checks (1) endpoints near start/goal, (2) the path is feasible under
    `cost_map` (no untraversable cells along it), (3) stays in bounds,
    (4) doesn't touch a rock under the hidden true cost, and (5) terrain
    cost <= expert bar. Prints a one-line summary. To score paths under your
    own cost map without invoking the bar, use path_cost instead.

    The bar (EXPERT_COST * TOL) has comfortable tolerance: an expert-like path
    that avoids the costly terrain clears it -- you don't need to match the
    expert exactly. The bar itself isn't exposed; treat this PASS/FAIL line as
    your feedback signal and iterate against it.
    '''
    path = np.asarray(path, float)
    start_ok = bool(np.linalg.norm(path[0]  - start) < 5)
    goal_ok  = bool(np.linalg.norm(path[-1] - goal)  < 5)
    rs = _resample_steps(path)
    # Feasibility flags from the resampled points. A "high" cell is one whose
    # cost is >= _HI (half the rock penalty) -- i.e. a rock / forbidden cell.
    if rs is None:
        model_feasible = rock_hit = out_of_bounds = False
    else:
        rx, ry, in_bounds = rs
        out_of_bounds = bool(not in_bounds.all())
        ryc, rxc = np.clip(ry, 0, H - 1), np.clip(rx, 0, W - 1)
        model_feasible = not bool((in_bounds &
                                   (np.asarray(cost_map, float)[ryc, rxc] >= _HI)).any())
        rock_hit = bool((in_bounds & (_TRUE_COST_PEN[ryc, rxc] >= _HI)).any())
    bare_cost = path_cost(path, _TRUE_COST_BARE)   # honest terrain-only cost
    bar = EXPERT_COST * TOL
    success = bool(start_ok and goal_ok and model_feasible
                   and not rock_hit and not out_of_bounds
                   and bare_cost <= bar)
    print(f"start_ok={start_ok} goal_ok={goal_ok} "
          f"model_feasible={model_feasible} rock_hit={rock_hit} "
          f"out_of_bounds={out_of_bounds} "
          f"cost={bare_cost:.1f} (bar={bar:.1f}) -> {'PASS' if success else 'FAIL'}")
    return success


def cost_map_baseline(field):
    '''Wrong-but-runnable (H,W) linear cost: 1 + 5*slope (ignores mud),
    rocks at ROCK_PENALTY. Lets you run the planner before learning the cost.'''
    cm = 1.0 + 5.0 * field[..., SLOPE]
    cm[field[..., ROCK] == 1] = ROCK_PENALTY
    return cm


def api_help():
    '''Print the public API the candidate works against.'''
    print('''Data:
  field : (H, W, 3) float -- channels ROCK=0 (binary), MUD=1 (0..1), SLOPE=2 (0..1)
  demos : list of expert (T, 2) (x, y) paths (their OWN start/goals, not yours)
  start, goal : (x, y) endpoints YOUR path must connect (x=col, y=row)
  H, W  : grid size

Functions (do not edit -- imported from challenge_utils):
  show(paths=None, cost_map=None, title='')  -> plot terrain/cost + demos + paths
  cost_map_baseline(field) -> (H, W)         -> wrong-but-runnable linear cost
  path_cost(path, cost_map) -> float          -> integrate a cost along a path
  evaluate(path, cost_map) -> bool            -> official PASS/FAIL scorer

You implement:
  plan(cost_map, ...) -> (T, 2) path
  cost_map_learned(field, demos) -> (H, W) cost inferred from the demos''')


__all__ = ['field', 'demos', 'meta', 'start', 'goal', 'H', 'W', 'ROCK', 'MUD', 'SLOPE', 'EXPERT_COST', 'TOL', 'ROCK_PENALTY', 'show', 'path_cost', 'evaluate', 'cost_map_baseline', 'api_help', 'plt', 'np']
