"""
challenge_utils_p2 -- prebuilt helpers for the planner-only Rover challenge.

GENERATED by build_notebooks_p2.py -- do not hand-edit. Loads the terrain data
and defines the visualizer, the official metric, and the GIVEN cost map so the
candidate only has to write `plan`. The cost map here is the real objective (not
hidden): minimize its path-integral from start to goal.
"""
import os
import numpy as np
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))

def _load(name):
    return os.path.join(_HERE, name)

field = np.load(_load('field_p2.npy'))                       # (H, W, 3)
meta  = np.load(_load('meta_p2.npz'))
start, goal = meta['start'], meta['goal']
H, W = field.shape[:2]
ROCK, MUD, SLOPE = 0, 1, 2


def show(paths=None, cost_map=None, title=''):
    '''Plot the cost map (or the terrain) and any candidate paths (lime), with
    start (white o) and goal (white *).'''
    fig, ax = plt.subplots(figsize=(6, 6))
    grid = np.asarray(cost_map if cost_map is not None else meta['true_cost'], float)
    rock = field[..., ROCK] == 1
    terrain = grid[~rock]
    cmap = plt.get_cmap('viridis').copy()
    cmap.set_over('0.6')   # rocks shown distinctly (gray)
    vmin = float(terrain.min()) if terrain.size else 0.0
    vmax = float(terrain.max()) if terrain.size else 1.0
    ax.imshow(grid, origin='lower', cmap=cmap, vmin=vmin, vmax=vmax)
    if paths is not None:
        if isinstance(paths, np.ndarray) and paths.ndim == 2:
            paths = [paths]
        for p in paths:
            p = np.asarray(p)
            ax.plot(p[:, 0], p[:, 1], 'lime', lw=2)
    ax.plot(*start, 'wo', ms=8); ax.plot(*goal, 'w*', ms=14)
    ax.set_title(title); ax.set_xlim(0, W); ax.set_ylim(0, H)
    plt.show()


# ===== PRE-BUILT METRIC -- see docstrings for path_cost/evaluate.
OPTIMAL_COST = float(meta['optimal_cost'])     # cost of grid A* on the cost map
TOL = float(meta['tol'])
_TRUE_COST = meta['true_cost']                 # (H,W) scoring grid (== cost_map)
_ROCK = float(meta['rock_sentinel'])           # cells >= this are rock
_STEP = 0.5                                    # path-integral resampling (cells)
ROCK_PENALTY = 1e6
_HI = ROCK_PENALTY / 2                          # cells >= this count as "rock"
_TRUE_COST_PEN  = np.where(_TRUE_COST >= _ROCK, ROCK_PENALTY, _TRUE_COST)
_TRUE_COST_BARE = np.where(_TRUE_COST >= _ROCK, 0.0,          _TRUE_COST)

def _resample_steps(path):
    '''Resample `path` to ~uniform _STEP spacing; return (rx, ry, in_bounds).'''
    path = np.asarray(path, float)
    seg = np.linalg.norm(np.diff(path, axis=0), axis=1)
    L = float(seg.sum())
    if L < 1e-9:
        return None
    s = np.concatenate([[0.0], np.cumsum(seg)])
    n = max(2, int(L / _STEP) + 1)
    u = np.linspace(0, L, n)
    xs = np.interp(u, s, path[:, 0]); ys = np.interp(u, s, path[:, 1])
    rx = np.rint(xs).astype(np.intp)
    ry = np.rint(ys).astype(np.intp)
    in_bounds = (rx >= 0) & (rx <= W - 1) & (ry >= 0) & (ry <= H - 1)
    return rx, ry, in_bounds

def path_cost(path, cost_map):
    '''Integrate cost_map along path; return total cost as a float (lower is
    better, empty path -> inf). Resamples to ~uniform spacing first, so the
    result is independent of waypoint count. Score candidate paths with this
    inside your planner. Out-of-bounds points are charged ROCK_PENALTY.
    '''
    cost_map = np.asarray(cost_map, float)
    if cost_map.shape != (H, W):
        raise ValueError(f'cost_map must have shape {(H, W)}, got {cost_map.shape}')
    rs = _resample_steps(path)
    if rs is None:
        return float('inf')
    rx, ry, in_bounds = rs
    cells = np.where(in_bounds, cost_map[np.clip(ry, 0, H - 1), np.clip(rx, 0, W - 1)],
                     ROCK_PENALTY)
    return float(cells.sum() * _STEP)

def evaluate(path, cost_map):
    '''Official PASS/FAIL scorer. Returns True iff the path passes.

    Checks (1) endpoints near start/goal, (2) the path is feasible under
    `cost_map` (no untraversable cells along it), (3) stays in bounds,
    (4) doesn't touch a rock, and (5) cost <= the near-optimal bar. Prints a
    one-line summary.

    The bar (OPTIMAL_COST * TOL) is the cost of an optimal grid planner on this
    cost map times a comfortable tolerance -- so a near-optimal path clears it.
    Treat this PASS/FAIL line as your feedback signal.
    '''
    path = np.asarray(path, float)
    start_ok = bool(np.linalg.norm(path[0]  - start) < 5)
    goal_ok  = bool(np.linalg.norm(path[-1] - goal)  < 5)
    rs = _resample_steps(path)
    if rs is None:
        model_feasible = rock_hit = out_of_bounds = False
    else:
        rx, ry, in_bounds = rs
        out_of_bounds = bool(not in_bounds.all())
        ryc, rxc = np.clip(ry, 0, H - 1), np.clip(rx, 0, W - 1)
        model_feasible = not bool((in_bounds &
                                   (np.asarray(cost_map, float)[ryc, rxc] >= _HI)).any())
        rock_hit = bool((in_bounds & (_TRUE_COST_PEN[ryc, rxc] >= _HI)).any())
    bare_cost = path_cost(path, _TRUE_COST_BARE)   # terrain-only cost (rocks zeroed)
    bar = OPTIMAL_COST * TOL
    success = bool(start_ok and goal_ok and model_feasible
                   and not rock_hit and not out_of_bounds
                   and bare_cost <= bar)
    print(f"start_ok={start_ok} goal_ok={goal_ok} "
          f"model_feasible={model_feasible} rock_hit={rock_hit} "
          f"out_of_bounds={out_of_bounds} "
          f"cost={bare_cost:.1f} (bar={bar:.1f}) -> {'PASS' if success else 'FAIL'}")
    return success


def cost_map(field):
    '''The (H,W) cost grid you must plan under (this IS the objective -- lower
    path-integral is better). Cells >= ROCK_PENALTY/2 are untraversable
    (obstacles). Pass this to your plan() and to evaluate().'''
    cm = 1.0 + 6.0 * field[..., MUD] + 4.0 * field[..., SLOPE]
    cm[field[..., ROCK] == 1] = ROCK_PENALTY
    return cm


def api_help():
    '''Print the public API the candidate works against.'''
    print('''Data:
  start, goal : (x, y) endpoints YOUR path must connect (x=col, y=row)
  H, W  : grid size
  field : raw terrain array -- just pass it to cost_map(field)

Functions (do not edit -- imported from challenge_utils_p2):
  cost_map(field) -> (H, W)                   -> the GIVEN cost grid you plan under
                                                 (cells >= ROCK_PENALTY/2 = obstacle)
  show(paths=None, cost_map=None, title='')  -> plot the cost grid + your paths
  path_cost(path, cost_map) -> float          -> integrate a cost along a path
  evaluate(path, cost_map) -> bool            -> official PASS/FAIL scorer

You implement (ONE function):
  plan(cost_map) -> (T, 2) near-optimal (x,y) path from start to goal''')


__all__ = ['field', 'meta', 'start', 'goal', 'H', 'W', 'ROCK', 'MUD', 'SLOPE', 'OPTIMAL_COST', 'TOL', 'ROCK_PENALTY', 'show', 'path_cost', 'evaluate', 'cost_map', 'api_help', 'plt', 'np']
