"""
challenge_utils_p1 -- prebuilt helpers for the 30-minute Rover planning challenge.

GENERATED by build_notebooks_p1.py -- do not hand-edit. Loads the terrain data
and defines the visualizer, the official metric, and a COMPLETE A* planner
(`astar_plan`) so the candidate only has to write `cost_map_learned`. The true
terrain cost stays hidden behind `path_cost` / `evaluate` (it lives in
meta['true_cost'] as an opaque grid); recovering it from the demos is the point,
so resist peeking here.

The terrain has only mud and slope -- there are no rocks / impassable cells, so
every cell is traversable at a finite cost.

Convention: all points are (row, col), so a path point p indexes a cost map
directly as cost_map[p[0], p[1]]. features[r, c] is the 2-vector at that cell.
"""
import os
import heapq
import numpy as np
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))

def _load(name):
    return os.path.join(_HERE, name)

features = np.load(_load('field_p1.npy'))                    # (H, W, 2) tensor
demos = np.load(_load('demos_p1.npy'), allow_pickle=True)    # object array of (T,2) (row,col)
meta  = np.load(_load('meta_p1.npz'))
start, goal = meta['start'], meta['goal']                    # (row, col)
H, W = features.shape[:2]
MUD, SLOPE = 0, 1


def show(paths=None, cost_map=None, title=''):
    '''Plot a cost map (or the terrain), the expert demos (gray), and any
    candidate paths (lime), with start (white o) and goal (white *). Points are
    (row, col); the plot puts col on the x-axis and row on the y-axis.'''
    fig, ax = plt.subplots(figsize=(6, 6))
    grid = np.asarray(cost_map if cost_map is not None else meta['true_cost'], float)
    ax.imshow(grid, origin='lower', cmap='viridis')
    for d in demos:
        d = np.asarray(d)
        ax.plot(d[:, 1], d[:, 0], '0.7', lw=1, alpha=.7)
        ax.plot(d[0, 1],  d[0, 0],  'o', color='0.5', ms=3, alpha=.8)
        ax.plot(d[-1, 1], d[-1, 0], '*', color='0.5', ms=5, alpha=.8)
    if paths is not None:
        if isinstance(paths, np.ndarray) and paths.ndim == 2:
            paths = [paths]
        for p in paths:
            p = np.asarray(p)
            ax.plot(p[:, 1], p[:, 0], 'lime', lw=2)
    ax.plot(start[1], start[0], 'wo', ms=8); ax.plot(goal[1], goal[0], 'w*', ms=14)
    ax.set_title(title); ax.set_xlim(0, W); ax.set_ylim(0, H)
    plt.show()


# ===== PRE-BUILT METRIC -- see docstrings for path_cost/evaluate.
# The true per-step terrain cost is an opaque grid in meta['true_cost']; don't
# peek -- recovering it from the demos is the point of the challenge.
OPTIMAL_COST = float(meta['optimal_cost'])     # cost of A* on the TRUE cost map
TOL = float(meta['tol'])
_TRUE_COST = np.asarray(meta['true_cost'], float)  # (H,W) opaque scoring grid
_STEP = 0.5                                    # path-integral resampling (cells)

def _resample_steps(path):
    '''Resample (row,col) `path` to ~uniform _STEP spacing; return
    (rows, cols, in_bounds) as rounded int cell indices.'''
    path = np.asarray(path, float)
    seg = np.linalg.norm(np.diff(path, axis=0), axis=1)
    L = float(seg.sum())
    if L < 1e-9:
        return None
    s = np.concatenate([[0.0], np.cumsum(seg)])
    n = max(2, int(L / _STEP) + 1)
    u = np.linspace(0, L, n)
    rr = np.interp(u, s, path[:, 0]); cc = np.interp(u, s, path[:, 1])
    rows = np.rint(rr).astype(np.intp)
    cols = np.rint(cc).astype(np.intp)
    in_bounds = (rows >= 0) & (rows <= H - 1) & (cols >= 0) & (cols <= W - 1)
    return rows, cols, in_bounds

_OOB_PENALTY = 1e6   # per-sample charge for an out-of-bounds path point

def path_cost(path, cost_map):
    '''Integrate cost_map along a (row,col) path; return total cost (lower is
    better, empty path -> inf). Resamples to ~uniform spacing first, so the
    result is independent of waypoint count. Out-of-bounds points are charged a
    large penalty, so a path that leaves the grid is scored as very costly.
    '''
    cost_map = np.asarray(cost_map, float)
    if cost_map.shape != (H, W):
        raise ValueError(f'cost_map must have shape {(H, W)}, got {cost_map.shape}')
    rs = _resample_steps(path)
    if rs is None:
        return float('inf')
    rows, cols, in_bounds = rs
    cells = np.where(in_bounds, cost_map[np.clip(rows, 0, H - 1), np.clip(cols, 0, W - 1)],
                     _OOB_PENALTY)
    return float(cells.sum() * _STEP)

def evaluate(path, cost_map=None):
    '''Official PASS/FAIL scorer. Returns True iff the path passes.

    `path` is an (T,2) array of (row,col) points. Checks (1) endpoints near
    start/goal, (2) the path stays in bounds, and (3) its terrain cost (under the
    hidden true cost) is <= the near-optimal bar. Prints a one-line summary.
    `cost_map` is accepted for backwards compatibility but not used -- there are
    no impassable cells, so scoring depends only on the true terrain cost.

    The bar (OPTIMAL_COST * TOL) is the cost of the provided `astar_plan` on the
    TRUE cost map, times a comfortable tolerance -- so a cost map that ranks the
    terrain about like the experts do clears it. The bar itself isn't exposed;
    treat this PASS/FAIL line as your feedback signal.
    '''
    path = np.asarray(path, float)
    start_ok = bool(np.linalg.norm(path[0]  - start) < 5)
    goal_ok  = bool(np.linalg.norm(path[-1] - goal)  < 5)
    rs = _resample_steps(path)
    out_of_bounds = True if rs is None else bool(not rs[2].all())
    cost = path_cost(path, _TRUE_COST)   # true terrain cost along the path
    bar = OPTIMAL_COST * TOL
    success = bool(start_ok and goal_ok and not out_of_bounds and cost <= bar)
    print(f"start_ok={start_ok} goal_ok={goal_ok} out_of_bounds={out_of_bounds} "
          f"cost={cost:.1f} (bar={bar:.1f}) -> {'PASS' if success else 'FAIL'}")
    return success


def astar_plan(cost_map):
    '''PROVIDED planner (do not edit -- just call it). Returns a near-optimal
    (T,2) (row,col) path from start to goal under the given (H,W) cost_map, found
    by 8-connected grid A*. The move cost between adjacent cells is the
    destination cell cost scaled by the step length (1 or sqrt(2)), matching
    path_cost's integral, so minimizing A*'s path here also minimizes the scored
    cost.'''
    cm = np.asarray(cost_map, float)
    if cm.shape != (H, W):
        raise ValueError(f'cost_map must have shape {(H, W)}, got {cm.shape}')

    def to_cell(p):                       # (row,col) -> int (row, col)
        return (int(np.clip(round(float(p[0])), 0, H - 1)),
                int(np.clip(round(float(p[1])), 0, W - 1)))
    sr, sc = to_cell(start)
    gr, gc = to_cell(goal)

    def h(r, c):
        return float(np.hypot(r - gr, c - gc))

    nbrs = [(-1, 0), (1, 0), (0, -1), (0, 1),
            (-1, -1), (-1, 1), (1, -1), (1, 1)]
    g = np.full((H, W), np.inf)
    g[sr, sc] = 0.0
    came = {}
    pq = [(h(sr, sc), sr, sc)]
    while pq:
        _, r, c = heapq.heappop(pq)
        if (r, c) == (gr, gc):
            break
        if g[r, c] == np.inf:
            continue
        for dr, dc in nbrs:
            nr, nc = r + dr, c + dc
            if not (0 <= nr < H and 0 <= nc < W):
                continue
            cell = cm[nr, nc]
            ng = g[r, c] + cell * float(np.hypot(dr, dc))
            if ng < g[nr, nc]:
                g[nr, nc] = ng
                came[(nr, nc)] = (r, c)
                heapq.heappush(pq, (ng + h(nr, nc), nr, nc))

    if not np.isfinite(g[gr, gc]):
        # No route reached the goal (shouldn't happen -- every cell is finite).
        # Return the straight line so the metric can still score/fail it.
        return np.linspace(start, goal, 60)
    cells = [(gr, gc)]
    while cells[-1] != (sr, sc):
        cells.append(came[cells[-1]])
    cells.reverse()
    return np.array([[r, c] for (r, c) in cells], dtype=float)


def run_and_score(cost_map_learned):
    '''Route the provided planner with your learned cost, plot the result, and
    print the official PASS/FAIL line. Pass your `cost_map_learned` function.'''
    cm = cost_map_learned(features, demos)
    path = astar_plan(cm)
    show(path, cost_map=cm, title='planned path over your learned cost map')
    show(path, title='planned path over the true terrain cost')
    return evaluate(path)


__all__ = ['features', 'demos', 'meta', 'start', 'goal', 'H', 'W', 'MUD', 'SLOPE', 'OPTIMAL_COST', 'TOL', 'show', 'astar_plan', 'run_and_score', 'plt', 'np']
