"""
viz_p1 -- plotting + build/run helpers for the C++ Rover challenge (Colab).

GENERATED by build_cpp_notebooks_p1.py -- do not hand-edit. show_cpp renders a
viz dump written by the C++ show(); build_and_run compiles a driver, runs it, and
renders its outputs. The candidate imports both from the setup cell.
"""
import subprocess
import numpy as np
import matplotlib.pyplot as plt


def show_cpp(bin_path, title=''):
    """Render a viz dump written by the C++ show() with matplotlib. Points in the
    dump are (row, col); the plot puts col on the x-axis and row on the y-axis."""
    with open(bin_path, 'rb') as f:
        H, Wd = np.fromfile(f, np.int32, 2)
        grid = np.fromfile(f, np.float64, H * Wd).reshape(H, Wd)
        rock = np.fromfile(f, np.uint8, H * Wd).reshape(H, Wd).astype(bool)
        sr, sc, gr, gc = np.fromfile(f, np.float64, 4)   # start/goal (row,col)
        def read_paths():
            n = int(np.fromfile(f, np.int32, 1)[0])
            out = []
            for _ in range(n):
                T = int(np.fromfile(f, np.int32, 1)[0])
                out.append(np.fromfile(f, np.float64, T * 2).reshape(T, 2))
            return out
        demos = read_paths()
        paths = read_paths()

    fig, ax = plt.subplots(figsize=(6, 6))
    terrain = grid[~rock]
    cmap = plt.get_cmap('viridis').copy()
    cmap.set_over('0.6')                      # rocks shown distinctly (gray)
    vmin = float(terrain.min()) if terrain.size else 0.0
    vmax = float(terrain.max()) if terrain.size else 1.0
    disp = np.where(rock, vmax + 1.0, grid)   # push rocks past vmax -> 'over'
    ax.imshow(disp, origin='lower', cmap=cmap, vmin=vmin, vmax=vmax)
    for d in demos:                           # d columns are (row, col)
        ax.plot(d[:, 1], d[:, 0], '0.7', lw=1, alpha=.7)
        ax.plot(d[0, 1],  d[0, 0],  'o', color='0.5', ms=3, alpha=.8)
        ax.plot(d[-1, 1], d[-1, 0], '*', color='0.5', ms=5, alpha=.8)
    for p in paths:
        ax.plot(p[:, 1], p[:, 0], 'lime', lw=2)
    ax.plot(sc, sr, 'wo', ms=8); ax.plot(gc, gr, 'w*', ms=14)
    ax.set_title(title); ax.set_xlim(0, Wd); ax.set_ylim(0, H)
    plt.show()


def build_and_run(main_cpp, views, std='c++17', opt='-O2'):
    """Compile `main_cpp` with g++, run ./app_p1, then show_cpp each (bin, title).

    `views` is a list of (bin_file, plot_title). Compiler diagnostics are printed
    verbatim so g++ errors on your learn_p1.hpp stay visible.
    """
    r = subprocess.run(['g++', opt, '-std=' + std, main_cpp, '-o', 'app_p1'],
                       capture_output=True, text=True)
    print(r.stderr or 'compiled OK')
    if r.returncode != 0:
        return
    out = subprocess.run(['./app_p1'], capture_output=True, text=True)
    print(out.stdout)
    if out.stderr:
        print(out.stderr)
    for bin_file, title in views:
        show_cpp(bin_file, title)
